var fs = require('fs');
let amount = 5

function Generate() {
var mathA = Math.floor(Math.random() * 10)
var mathB = Math.floor(Math.random() * 10)
var mathC = Math.floor(Math.random() * 10)
var mathD = Math.floor(Math.random() * 10)
var mathE = Math.floor(Math.random() * 10)
return(`0011` + mathA + mathB + mathC + mathD + mathE)
}

fs.writeFileSync(`savings.txt`, `
//////////////
BEGIN LIST
//////////////
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
${Generate()},
//////////////
END LIST
//////////////`)
